using CentralOrchestrator.Services;
using Common.Contracts;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System.Text.Json;

namespace SqlDataAgent;

public class SqlQueueWorker : BackgroundService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<SqlQueueWorker> _logger;
    private const string AgentId = "sql-data-agent";

    public SqlQueueWorker(IServiceProvider serviceProvider, ILogger<SqlQueueWorker> logger)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("SqlDataAgent Database Queue Worker started. Agent ID: {AgentId}", AgentId);

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                using var scope = _serviceProvider.CreateScope();
                var queueService = scope.ServiceProvider.GetRequiredService<IDatabaseQueueService>();

                var pendingTasks = await queueService.GetPendingTasksForAgentAsync(AgentId, limit: 5);

                foreach (var task in pendingTasks)
                {
                    _logger.LogInformation("Claiming Task '{TaskGuid}' (Action: '{Action}')", task.TaskGuid, task.Action);
                    
                    var claimed = await queueService.ClaimTaskAsync(task.TaskGuid);
                    if (!claimed) continue;

                    try
                    {
                        var resultMarkdown = ExecuteSqlQuery(task.PayloadJson);

                        var resultObj = new
                        {
                            agentId = AgentId,
                            action = task.Action,
                            output = resultMarkdown
                        };

                        await queueService.UpdateTaskResultAsync(task.TaskGuid, new UpdateTaskResultRequest(
                            Status: "Completed",
                            ResultJson: JsonSerializer.Serialize(resultObj)
                        ));

                        _logger.LogInformation("Successfully completed Task '{TaskGuid}'", task.TaskGuid);
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "Failed to execute Task '{TaskGuid}'", task.TaskGuid);
                        await queueService.UpdateTaskResultAsync(task.TaskGuid, new UpdateTaskResultRequest(
                            Status: "Failed",
                            ErrorMessage: ex.Message
                        ));
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in SqlQueueWorker loop");
            }

            await Task.Delay(2000, stoppingToken);
        }
    }

    private static string ExecuteSqlQuery(string payloadJson)
    {
        string sql = "SELECT Region, SUM(Amount) AS TotalSales FROM Sales_2026 GROUP BY Region";
        try
        {
            using var doc = JsonDocument.Parse(payloadJson);
            if (doc.RootElement.TryGetProperty("sql", out var sqlProp) && !string.IsNullOrWhiteSpace(sqlProp.GetString()))
            {
                sql = sqlProp.GetString()!;
            }
        }
        catch { }

        // Simulated safe database execution returning Markdown table output
        return $@"### SQL Execution Report
**Executed Query:** `{sql}`

| Region | Total Sales ($) | Record Count | Status |
| :--- | :--- | :--- | :--- |
| North America | $1,245,000 | 450 | Verified |
| Europe | $980,500 | 310 | Verified |
| Asia Pacific | $1,420,000 | 520 | Verified |
| Latin America | $650,000 | 190 | Verified |

*Generated by SqlDataAgent at {DateTimeOffset.UtcNow:u}*";
    }
}
